version: '3.9'

services:
  redis:
    image: redis:7.0.5
    restart: always
  
  backend:
    build: .
    depends_on:
      - redis
    volumes:
      - ./src:/src
    links:
      - "redis"
    ports:
      - "8080:8080"
